repos:
  - repo: local
    hooks:
      - id: codespell
        name: codespell
        entry: uv run --frozen codespell --toml pyproject.toml
        language: system
        types: [text]

      - id: ruff-check
        name: ruff check
        entry: uv run --frozen ruff check --force-exclude --fix
        language: system
        types_or: [python, pyi]
        require_serial: true

      - id: ruff-format
        name: ruff format
        entry: uv run --frozen ruff format --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true

      - id: mypy
        name: mypy
        entry: uv run --frozen mypy
        language: system
        types_or: [python, pyi]
        require_serial: true
        files: ^zha/

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.11.16
    hooks:
      - id: uv-lock
        args: ["--check"]
