"""Regenerate per-module mypy disable_error_code overrides in pyproject.toml.

Usage:
    python -m tools.regenerate_mypy_ignores
"""

from collections import defaultdict
from pathlib import Path
import re

from mypy import api as mypy_api

START_MARKER = "# Autogenerated mypy overrides: start"
END_MARKER = "# Autogenerated mypy overrides: end"

# The base type-checking strictness ZHA enforces, expressed as CLI flags so the
# run is independent of the per-module overrides we are about to regenerate.
# Keep in sync with the non-override settings in [tool.mypy] in pyproject.toml.
MYPY_FLAGS = [
    "zha",
    "--config-file=/dev/null",
    "--python-version=3.12",
    "--ignore-missing-imports",
    "--follow-imports=silent",
    "--check-untyped-defs",
    "--disallow-incomplete-defs",
    "--disallow-untyped-calls",
    "--disallow-untyped-defs",
    "--no-implicit-optional",
    "--strict-equality",
    "--warn-redundant-casts",
    "--warn-return-any",
    "--warn-unreachable",
    "--warn-unused-ignores",
    "--no-error-summary",
]


def run_mypy() -> list[str]:
    """Run mypy with no error codes disabled and capture output."""
    stdout, stderr, _ = mypy_api.run(MYPY_FLAGS)
    return stdout.splitlines() + stderr.splitlines()


def parse_errors(lines: list[str]) -> dict[str, dict[str, int]]:
    """Parse mypy output into {module: {error_code: count}}."""
    errors_by_module: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))

    for line in lines:
        match = re.match(r"^([^:]+):.* \[([a-z-]+)\]$", line.strip())
        if match:
            filepath, error_code = match.groups()
            module = filepath.replace("/", ".").replace(".py", "")
            module = module.removesuffix(".__init__")
            errors_by_module[module][error_code] += 1

    return dict(errors_by_module)


def format_override(module: str, codes: dict[str, int]) -> str:
    """Format a single [[tool.mypy.overrides]] section."""
    lines = [
        "[[tool.mypy.overrides]]",
        f'module = "{module}"',
        "disable_error_code = [",
    ]
    for code in sorted(codes.keys()):
        lines.append(f'    "{code}",  # {codes[code]}')  # noqa: PERF401
    lines.append("]")
    return "\n".join(lines)


def generate_overrides(errors_by_module: dict[str, dict[str, int]]) -> str:
    """Generate all override sections, sorted easiest-to-fix first."""
    # Sort by (total error count, module name) so easiest fixes are at the top
    sorted_modules = sorted(
        errors_by_module.items(), key=lambda x: (sum(x[1].values()), x[0])
    )

    sections = [format_override(module, codes) for module, codes in sorted_modules]
    return "\n\n".join(sections)


def main() -> None:
    """Entry point."""
    pyproject_path = Path("pyproject.toml")
    content = pyproject_path.read_text()

    lines = run_mypy()
    errors_by_module = parse_errors(lines)
    overrides_content = generate_overrides(errors_by_module)

    # Replace content between markers
    pattern = re.compile(
        rf"({re.escape(START_MARKER)})\n.*?\n({re.escape(END_MARKER)})",
        re.DOTALL,
    )
    new_content = pattern.sub(rf"\1\n{overrides_content}\n\2", content)

    if new_content != content:
        pyproject_path.write_text(new_content)


if __name__ == "__main__":
    main()
