name: Publish distributions to PyPI

on:
  release:
    types:
      - published

jobs:
  shared-build-and-publish:
    uses: zigpy/workflows/.github/workflows/publish-to-pypi.yml@dm/update-ci-03272024
    with:
      PYTHON_VERSION_DEFAULT: 3.12
